<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWZSjlUL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWZSjlUL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWZSjlUL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWZSjlUL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWZSjlUL\App_KernelDevDebugContainer([
    'container.build_hash' => 'WZSjlUL',
    'container.build_id' => '655007a9',
    'container.build_time' => 1727185326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWZSjlUL');
