<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOiRrMiM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOiRrMiM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOiRrMiM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOiRrMiM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOiRrMiM\App_KernelDevDebugContainer([
    'container.build_hash' => 'OiRrMiM',
    'container.build_id' => 'd7875d30',
    'container.build_time' => 1727189590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOiRrMiM');
